app:
   name: QuantumMesh
server:
   port: 9091
logging:
   level:
      org.springframework.security: TRACE
      org.springframework.cloud.gateway: TRACE
spring:
   profiles:
      active: dev
   application.name: APIGateway
   data:
      mongodb:
         uri:  #==> Update as per requirement
         database: db_route # update database name
rsa:
   key:
      secret: WVZgXCnLoulqw1G97eFHV32P28x3uYbw9jcwTwuiM+ZI75od4y2Ln7bviuuxedZBKXF4VJe/Vp4VvT8/R6XEBQ== # used to authenticate JWT token
